export const people = [
    { name: "Lucas Martin", location: "kitchen", price: 3 },
    { name: "Emma Johnson", location: "kitchen" },
    { name: "Alexandre Dubois", location: "kitchen", price: 4 },
    { name: "Sophie Leroy", location: "kitchen" },
    { name: "Nathan Garcia", location: "kitchen" },
    { name: "Eva Davis", location: "kitchen", price: 30 },
    { name: "Thomas Smith", location: "kitchen" },
    { name: "Clara Martin", location: "kitchen" },
    { name: "Gabriel Jones", location: "kitchen", price: 40 },
    { name: "Léa Dupont", location: "kitchen" },
    { name: "Antoine Taylor", location: "kitchen" },
    { name: "Camille Roberts", location: "kitchen", price: 18 },
    { name: "Hugo Brown", location: "kitchen" },
    { name: "Chloé Martin", location: "kitchen" },
    { name: "Louis Wilson", location: "kitchen", price: 37 },
    { name: "Lola Anderson", location: "kitchen" },
    { name: "Maxime Miller", location: "kitchen" },
    { name: "Zoé Garcia", location: "kitchen", price: 29 },
    { name: "Mathis Davis", location: "kitchen" },
    { name: "Olivia Martin", location: "room", price: 25 },
    { name: "Noah Johnson", location: "room" },
    { name: "Sophia Dubois", location: "room", price: 12 },
    { name: "Liam Leroy", location: "room" },
    { name: "Emma Garcia", location: "room" },
    { name: "Jackson Davis", location: "room" },
    { name: "Ava Smith", location: "room" },
    { name: "Aiden Martin", location: "room" },
    { name: "Isabella Jones", location: "room" },
    { name: "Lucas Taylor", location: "room" },
    { name: "Mia Roberts", location: "room" },
    { name: "Caden Brown", location: "room" },
    { name: "Amelia Wilson", location: "room" },
    { name: "Logan Anderson", location: "room" },
    { name: "Ella Miller", location: "room" },
    { name: "Grayson Garcia", location: "room" },
    { name: "Lily Davis", location: "room" },
    { name: "Carter Martin", location: "room" },
    { name: "Abigail Anderson", location: "room" },
    { name: "Henry Wilson", location: "room", price: 6 }
  ];

